#!/usr/bin/python

import json
import sys
import re
from subprocess import call

# usage: this [ase files] output.png

# aseprite -b *.ase --sheet-pack --sheet atlas-bestfit.png --data atlas-bestfit.json


jfile = sys.argv[-1:][0][:-4] + ".json"
print("using json file " + jfile)

options = "--batch "
for filename in sys.argv[1:-1]:
    options += filename + " "
options += "--sheet-pack --sheet " + sys.argv[-1:][0] + " --data " + jfile + " --format json-array"
 
command=["/home/tom/software/bin/aseprite"]
command.extend(options.split(' '))


#print("\n\n exactly this:\n" + ' '.join([command, options]) + "\n\n")

call(command)
sprites = []
for filename in sys.argv[1:-1]:
    sprites.append(re.sub('[^a-zA-Z0-9]', '', filename.split('/')[-1:][0][:-4]))

sprnum = len(sprites)
print("found " + str(sprnum) + " sprites:\n" + '\n'.join(sprites))

print("opening " + jfile)
with open(jfile) as infile:
    data = json.load(infile)


j = {"sprites":[], "meta":{}}
for i in range(len(sprites)):
    j['sprites'].append({})
    j['sprites'][i]['name'] = sprites[i]
    j['sprites'][i]['frames'] = []
    for frame in data['frames']:
        if sprites[i] == re.sub(' [0-9]+\.ase|[^a-zA-Z0-9]','', frame['filename']):
            j['sprites'][i]['frames'].append(frame)
j['meta'] = data['meta']
j['meta']['sprnum'] = sprnum

#print("Okay, here's the json result:")
#print(json.dumps(j, indent=4))

with open(jfile, 'w') as outfile:
    json.dump(j, outfile)

print("done")
